#!/bin/bash

work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/openwrt"
version=$(git describe --always)

echo "Creating runtime Docker containers..."
for branch in $(cat ${platform_dir}/branches); do
  short_branch=$(echo $branch | cut -d ':' -f 4)
  branch=$(echo $branch | cut -d ':' -f 1)

  for architecture in $(cat ${platform_dir}/architectures); do
    image_name="wlanslovenija/openwrt-builder:v${version}_${short_branch}_${architecture}"

    echo -n "  - Building image ${image_name}... "
    docker run --rm wlanslovenija/openwrt-builder-stage-1:${branch}_${architecture} 2>/dev/null | \
      docker build --rm --force-rm -t ${image_name} - >/dev/null 2>/dev/null

    if [ "$?" == "0" ]; then
      echo "ok"
      #docker push ${image_name} 2>/dev/null || {
      #  echo "ERROR: Failed to push image!"
      #  exit 1
      #}
    else
      echo "(skipped)"
    fi
  done
done
