#!/bin/bash

openwrt_version="$1"
openwrt_target="$2"
openwrt_subtarget="$3"
work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/openwrt"

echo "Creating runtime Docker container for ${openwrt_version} ${openwrt_target} ${openwrt_subtarget}"

docker run --rm otvorenamreza/openwrt-imagebuilder-base:${openwrt_version}_${openwrt_target}_${openwrt_subtarget} 2>/dev/null | \
docker build --rm --force-rm -t wlanslovenija/openwrt-builder:${openwrt_version}_${openwrt_target}_${openwrt_subtarget} - >/dev/null 2>/dev/null
