#!/bin/bash -e

work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/openwrt"
docker_dir="${work_dir}/docker/openwrt"

branch=$1
[ -z "${branch}" ] && {
  echo "Usage: $0 <branch>"
  exit 1
}

cd ${work_dir}
docker build --rm -t wlanslovenija/firmware-base .
cd ${docker_dir}/buildsystem/${branch}
docker build --rm -t wlanslovenija/openwrt-buildsystem:${branch} .
cd ${work_dir}

