#!/bin/bash

template_buildsystem="
FROM wlanslovenija/firmware-base

MAINTAINER Jernej Kos <jernej@kos.mx>

RUN ./openwrt/scripts/prepare \${branch} \${path} \${rev} && \\\\
 rm -rf .git && \\\\
 chown -R builder:builder build
"

template_stage1="
FROM wlanslovenija/openwrt-buildsystem:\${branch}

MAINTAINER Jernej Kos <jernej@kos.mx>

RUN chown builder:builder /buildsystem/build && \\\\
 sudo -E -u builder ./openwrt/scripts/configure-platform \${architecture} && \\\\
 sudo -E -u builder ./openwrt/scripts/build-toolchain && \\\\
 sudo -E -u builder ./openwrt/scripts/build-imagebuilder && \\\\
 export version=\\\"\\\$(cat /buildsystem/build/openwrt/package/base-files/files/etc/version)\\\" && \\\\
 cd /buildsystem/build/release && \\\\
 mkdir -p /builder/imagebuilder && \\\\
 tar xf imagebuilder.tar.bz2 -C /builder/imagebuilder --strip-components 1 && \\\\
 mv packages /builder/packages && \\\\
 echo -n \\\"{\\\\\\\"platform\\\\\\\": \\\\\\\"openwrt\\\\\\\", \\\" > /builder/packages/metadata && \\\\
 echo -n \\\"\\\\\\\"architecture\\\\\\\": \\\\\\\"\${architecture}\\\\\\\", \\\" >> /builder/packages/metadata && \\\\
 echo \\\"\\\\\\\"version\\\\\\\": \\\\\\\"\\\${version}\\\\\\\"}\\\" >> /builder/packages/metadata && \\\\
 cp /buildsystem/openwrt/docker/Dockerfile.runtime /builder/Dockerfile && \\\\
 { rm -rf /buildsystem 2>/dev/null || true; }

WORKDIR /builder
CMD tar cvzhf - .
"

# ------------------------------------------------------------------------

work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/openwrt"
docker_dir="${work_dir}/docker/openwrt"

echo "Generating Dockerfiles..."
rm -rf ${docker_dir}
for branch in $(cat ${platform_dir}/branches); do
  path=$(echo $branch | cut -d ':' -f 2)
  rev=$(echo $branch | cut -d ':' -f 3)
  branch=$(echo $branch | cut -d ':' -f 1)

  # Buildsystem dockerfile
  dockerfile=$(eval "echo \"${template_buildsystem}\"")
  mkdir -p ${docker_dir}/buildsystem/${branch}
  echo "${dockerfile}" > ${docker_dir}/buildsystem/${branch}/Dockerfile

  for architecture in $(cat ${platform_dir}/architectures); do
    # Stage 1 dockerfile
    dockerfile=$(eval "echo \"${template_stage1}\"")
    mkdir -p "${docker_dir}/builder-stage-1/${branch}/${architecture}"
    echo "${dockerfile}" > "${docker_dir}/builder-stage-1/${branch}/${architecture}/Dockerfile"
  done
done
