#!/bin/bash

work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/lede"
build_dir="${work_dir}/build"
checkout_dir="${build_dir}/lede"
release_dir="${build_dir}/release"

if [ ! -f ${checkout_dir}/.toolchain_built ]; then
  echo "ERROR: Toolchain not built!"
  exit 1
fi

# Build imagebuilder.
echo "Building the imagebuilder..."
cd ${checkout_dir}
make "$@" || {
    echo "ERROR: Failed to build the imagebuilder!"
    exit 1
}

# Recreate release directory.
rm -rf ${release_dir}
mkdir -p ${release_dir}

echo "Extracting the imagebuilder..."
mv ${checkout_dir}/bin/targets/*/*/openwrt-imagebuilder-*.tar.xz ${release_dir}/imagebuilder.tar.xz

echo "Extracting packages..."
cd ${checkout_dir}/bin
mkdir -p ${release_dir}/packages

for package_dir in $(find -type d -name packages); do
    target_package_dir="${release_dir}/packages/${package_dir}"
    mkdir -p ${target_package_dir}
    mv ${checkout_dir}/bin/${package_dir}/* ${target_package_dir}/
done

cd -
