#!/bin/bash -e

work_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
platform_dir="${work_dir}/lede"
docker_dir="${work_dir}/docker/lede"

branch=$1
[ -z "${branch}" ] && {
  echo "Usage: $0 <branch> [<architectures>]"
  exit 1
}

architectures="$2"
if [ -z "${architectures}" ]; then
  architectures=$(cat ${platform_dir}/architectures)
fi

cd ${docker_dir}/builder-stage-1/${branch}

for architecture in ${architectures}; do
  cd ${architecture}
  docker build --rm -t wlanslovenija/lede-builder-stage-1:${branch}_${architecture} .
  cd ..
done

cd ${work_dir}
