#!/bin/bash
#
# nodewatcher firmware prepare script
#

BUILD_DIR=build

log()
{
  echo "[nw-firmware] prepare: $*"
}

# Check if all utilities that we need are ready for use
log "Checking for prepare-time dependencies..."

quilt=$(which quilt)
if [ "$quilt" == "" ]; then
  log "quilt not found."
  exit 1
fi

# Check for proper working directory
log "Checking working directory..."
if [[ ! -d scripts || ! -d openwrt ]]; then
  log "Invalid working directory!"
  exit 1
fi

workdir=$(pwd)
mkdir -p ${BUILD_DIR}

# Now that we have everything verified, first checkout the OpenWRT repository
openwrt_version=$(cat openwrt/version)
log "OpenWRT trunk version: ${openwrt_version}"
log "Checking out OpenWRT into ${BUILD_DIR}, this could take some time..."

OPENWRT_CHECKOUT_DIR=${workdir}/${BUILD_DIR}/openwrt
rm -rf ${OPENWRT_CHECKOUT_DIR}
svn co -q -r ${openwrt_version} svn://svn.openwrt.org/openwrt/trunk ${OPENWRT_CHECKOUT_DIR}

log "Purging .svn files from repository..."
find ${OPENWRT_CHECKOUT_DIR} -name .svn -type d -exec rm -rf "{}" \; 2>/dev/null

# Inject feeds and configurations
log "Configuring feeds..."
echo "src-hg nodewatcher http://dev.wlan-si.net/hg/firmware/packages/opkg" > ${OPENWRT_CHECKOUT_DIR}/feeds.conf
echo "src-svn openwrt svn://svn.openwrt.org/openwrt/packages" >> ${OPENWRT_CHECKOUT_DIR}/feeds.conf

# Patch OpenWRT
log "Applying patches for OpenWRT base tree..."
cd ${OPENWRT_CHECKOUT_DIR}
ln -s ${workdir}/openwrt/patches patches
quilt push -f -a

# Importing feeds
log "Importing feeds..."
./scripts/feeds update -a >/dev/null
./scripts/feeds install -a -p nodewatcher

for package in $(cat ${workdir}/openwrt/packages); do
  ./scripts/feeds install ${package}
done

# Preparation is now completed
log "Preparation completed, you may now build the firmware."
