#!/bin/bash
#
# nodewatcher firmware prepare script
#

BUILD_DIR=build

log()
{
  echo "[nw-firmware] prepare: $*"
}

# Check if all utilities that we need are ready for use
log "Checking for prepare-time dependencies..."

for program in quilt svn
do
  p=$(which $program)
  if [ "$p" == "" ]; then
    log "$program not found."
    exit 1
  fi
done

# Check for proper working directory
log "Checking working directory..."
if [[ ! -d scripts || ! -d openwrt ]]; then
  log "Invalid working directory!"
  exit 1
fi

workdir=$(pwd)
mkdir -p ${BUILD_DIR}

# Get version identifier
firmware_version=$(git describe --always)

# Now that we have everything verified, first checkout the OpenWRT repository
openwrt_version=$(cat openwrt/version)
openwrt_path=$(echo $openwrt_version | cut -d ':' -f 1)
openwrt_path_name="${openwrt_path//\//-}"
openwrt_path_name="${openwrt_path_name//_/-}"
openwrt_rev=$(echo $openwrt_version | cut -d ':' -f 2)

log "OpenWRT path: ${openwrt_path}"
log "OpenWRT revision: ${openwrt_rev}"
log "Checking out OpenWRT into ${BUILD_DIR}, this could take some time..."

OPENWRT_CHECKOUT_DIR=${workdir}/${BUILD_DIR}/openwrt
rm -rf ${OPENWRT_CHECKOUT_DIR}
svn co -q -r ${openwrt_rev} svn://svn.openwrt.org/openwrt/${openwrt_path} ${OPENWRT_CHECKOUT_DIR}

log "Purging .svn files from repository..."
find ${OPENWRT_CHECKOUT_DIR} -name .svn -type d -exec rm -rf "{}" \; 2>/dev/null

# Inject feeds and configurations
log "Configuring feeds..."
echo "src-git nodewatcher git://github.com/wlanslovenija/firmware-packages-opkg.git" > ${OPENWRT_CHECKOUT_DIR}/feeds.conf
echo "src-git routing git://github.com/openwrt-routing/packages.git" >> ${OPENWRT_CHECKOUT_DIR}/feeds.conf
cat ${workdir}/openwrt/feeds/${openwrt_path_name} >> ${OPENWRT_CHECKOUT_DIR}/feeds.conf

# Patch OpenWRT
log "Applying patches for OpenWRT base tree..."
cd ${OPENWRT_CHECKOUT_DIR}
ln -s ${workdir}/openwrt/patches/${openwrt_path_name} patches
quilt push -f -a

# Update version file and banner
echo "git.${firmware_version}" > package/base-files/files/etc/version
echo "
 +-------------------------------------------------+
 | wlan slovenia                  open.wlan-si.net |
 |          node                                   |
 +-------------------------------------------------+
 *) FIRMWARE VERSION: git.${firmware_version}
 
" > package/base-files/files/etc/banner

# Importing feeds
log "Importing feeds..."
./scripts/feeds update -a >/dev/null

for package in $(cat ${workdir}/openwrt/packages); do
  ./scripts/feeds install ${package}
done

# Preparation is now completed
log "Preparation completed, you may now build the firmware."
